defaults:
  - experiment: ppo_double_pendulum
  # - override hydra/hydra_logging: disabled
  # - override hydra/job_logging: disabled
  # - override hydra/launcher: joblib
  - _self_

# wandb configs
project: c4il
entity: ias-tudarmstadt
